<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 6/22/2016 at 12:25:26 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$names = addslashes($_POST['names']);
@$emailaddress = addslashes($_POST['email-address']);
@$message = addslashes($_POST['message']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $emailaddress\n"
  . "Reply-To: $emailaddress\n";
$pfw_subject = "Ask Question";
$pfw_email_to = "info@wildsafarisandtravel.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "names: $names\n"
. "emailaddress: $emailaddress\n"
. "message: $message\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location:http://www.wildsafarisandtravel.com/thankyou.html") ;
?>
