<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 6/22/2016 at 12:20:38 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$names = addslashes($_POST['names']);
@$emailaddress = addslashes($_POST['email-address']);
@$from = addslashes($_POST['from']);
@$to = addslashes($_POST['to']);
@$dateto = addslashes($_POST['date-to']);
@$numberofpeopleflying = addslashes($_POST['number-of-people-flying']);
@$chartermessage = addslashes($_POST['charter-message']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $emailaddress\n"
  . "Reply-To: $emailaddress\n";
$pfw_subject = "Charter Message";
$pfw_email_to = "info@wildsafarisandtravel.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "names: $names\n"
. "emailaddress: $emailaddress\n"
. "from: $from\n"
. "to: $to\n"
. "dateto: $dateto\n"
. "numberofpeopleflying: $numberofpeopleflying\n"
. "chartermessage: $chartermessage\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location:http://www.wildsafarisandtravel.com/thankyou.html") ;
?>
