<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 6/22/2016 at 12:22:07 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$names = addslashes($_POST['names']);
@$email = addslashes($_POST['email']);
@$phone-number = addslashes($_POST['phone-number']);
@$message = addslashes($_POST['message']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $email\n"
  . "Reply-To: $email\n";
$pfw_subject = "Contact us";
$pfw_email_to = "info@wildsafarisandtravel.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "names: $names\n"
. "email: $email\n"
. "phone-number: $phone-number\n"
. "message: $message\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ; 

header("Location:http://www.wildsafarisandtravel.com/thankyou.html") ;
?>
