<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 6/22/2016 at 12:13:54 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$names = addslashes($_POST['names']);
@$emailaddress = addslashes($_POST['email-address']);
@$hotelname = addslashes($_POST['hotel-name']);
@$checkindate = addslashes($_POST['check-in-date']);
@$checkoutdate = addslashes($_POST['check-out-date']);
@$hotelmessage = addslashes($_POST['hotel-message']);
@$numberofrooms = addslashes($_POST['number-of-rooms']);
@$numberofadults = addslashes($_POST['number-of-adults']);
@$numberofchildren = addslashes($_POST['number-of-children']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $emailaddress\n"
  . "Reply-To: $emailaddress\n";
$pfw_subject = "Hotel Booking";
$pfw_email_to = "info@wildsafarisandtravel.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "names: $names\n"
. "emailaddress: $emailaddress\n"
. "hotelname: $hotelname\n"
. "checkindate: $checkindate\n"
. "checkoutdate: $checkoutdate\n"
. "hotelmessage: $hotelmessage\n"
. "numberofrooms: $numberofrooms\n"
. "numberofadults: $numberofadults\n"
. "numberofchildren: $numberofchildren\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location:http://www.wildsafarisandtravel.com/thankyou.html") ;
?>
