<?php
# ----------------------------------------------------
# -----
# ----- This script was generated by PHP-Form Wizard 1.2.5 on 6/22/2016 at 12:22:07 PM
# -----
# ----- http://www.tools4php.com
# -----
# ----------------------------------------------------


// Receiving variables
@$pfw_ip= $_SERVER['REMOTE_ADDR'];
@$names = addslashes($_POST['names']);
@$emailaddress = addslashes($_POST['email-address']);
@$checkindate = addslashes($_POST['check-in-date']);
@$dateoutdate = addslashes($_POST['date-out-date']);
@$numberofadults = addslashes($_POST['number-of-adults']);
@$numberofchildren = addslashes($_POST['number-of-children']);
@$tourmessage = addslashes($_POST['tour-message']);

// Validation
//Sending Email to form owner
$pfw_header = "From: $emailaddress\n"
  . "Reply-To: $emailaddress\n";
$pfw_subject = "Tour Booking";
$pfw_email_to = "info@wildsafarisandtravel.com";
$pfw_message = "Visitor's IP: $pfw_ip\n"
. "names: $names\n"
. "emailaddress: $emailaddress\n"
. "checkindate: $checkindate\n"
. "dateoutdate: $dateoutdate\n"
. "numberofadults: $numberofadults\n"
. "numberofchildren: $numberofchildren\n"
. "tourmessage: $tourmessage\n";
@mail($pfw_email_to, $pfw_subject ,$pfw_message ,$pfw_header ) ;

header("Location:http://www.wildsafarisandtravel.com/thankyou.html") ;
?>
